<option value=""></option>
<option value="Agent">Agent</option>
<option value="Architect">Architect</option>
<option value="Blog">Blog</option>
<option value="Contractor">Contractor</option>
<option value="Distributor">Distributor</option>
<option value="Final Buyer">Final Buyer</option>
<option value="Freelancer">Freelancer</option>
<option value="Furniture store">Furniture store</option>
<option value="Hotel">Hotel</option>
<option value="Interior Designer">Interior Designer</option>
<option value="Interior Designer/Architect">Interior Designer/Architect</option>
<option value="Magazine">Magazine</option>
<option value="Newspaper">Newspaper</option>
<option value="Online Store">Online Store</option>
<option value="Publisher">Publisher</option>
<option value="Radio">Radio</option>
<option value="Restaurant">Restaurant</option>
<option value="TV">TV</option>
<option value="Other">Other</option>